lajujaya/door/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.door, name='door'),
    url(r'^solid-wooden-door/$', views.solid_wooden_door, name="solid_wooden_door"),
    url(r'^firedoor/$', views.firedoor, name="firedoor"),
    url(r'^MPC-design-door/$', views.MPC_design_door, name="MPC_design_door"),
]

lajujaya/doorlock/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.doorlock, name='doorlock'),
    # -----------------------------ST GUCHI------------------------------------
    url(r'^st-guchi/$', views.st_guchi, name="st_guchi"),
    url(r'^st-guchi/accessories$', views.st_guchi_accessories, name='st_guchi_accessories'),
    url(r'^st-guchi/cylindrical-lever$', views.st_guchi_cylindrical_lever, name="st_guchi_cylindrical_lever"),
    url(r'^st-guchi/cylindrical-lock$', views.st_guchi_cylindrical_lock, name="st_guchi_cylindrical_lock"),
    url(r'^st-guchi/deadbolt-lock$', views.st_guchi_deadbolt_lock, name="st_guchi_deadbolt_lock"),
    url(r'^st-guchi/door-closer$', views.st_guchi_door_closer, name="st_guchi_door_closer"),
    url(r'^st-guchi/handle-set$', views.st_guchi_handle_set, name="st_guchi_handle_set"),
    url(r'^st-guchi/lever-handle$', views.st_guchi_lever_handle, name="st_guchi_lever_handle"),
    url(r'^st-guchi/mortise-handle-set$', views.st_guchi_mortise_handle_set, name="st_guchi_mortise_handle_set"),
    url(r'^st-guchi/mortise-lock-and-hook-lock$', views.st_guchi_mortise_hook_lock, name="st_guchi_mortise_hook_lock"),
    url(r'^st-guchi/mortise-lock$', views.st_guchi_mortise_lock, name="st_guchi_mortise_lock"),
    url(r'^st-guchi/pad-lock$', views.st_guchi_pad_lock, name="st_guchi_pad_lock"),
    url(r'^st-guchi/profile-cylinder$', views.st_guchi_profile_cylinder, name="st_guchi_profile_cylinder"),
    url(r'^st-guchi/pull-handle$', views.st_guchi_pull_handle, name="st_guchi_pull_handle"),
    url(r'^st-guchi/tubular-lever$', views.st_guchi_tubular_lever, name="st_guchi_tubular_lever"),
    # --------------------------------IKAROS------------------------------------
    url(r'^ikaros/$', views.ikaros, name='ikaros'),
    url(r'^ikaros/cylindrical-lever$', views.ikaros_cylindrical_lever, name='ikaros_cylindrical_lever'),
    url(r'^ikaros/pad-lock$', views.ikaros_pad_lock, name='ikaros_pad_lock'),
    # -----------------------------DIGITAL DOOR LOCK--------------------------------
    url(r'^digital-door-lock/$', views.digital_doorlock, name='digital_doorlock'),
    url(r'^digital-door-lock/samsung$', views.digital_doorlock_samsung, name='digital_doorlock_samsung'),
    url(r'^digital-door-lock/gateman$', views.digital_doorlock_gateman, name='digital_doorlock_gateman'),
    # ---------------------------------HAFELE----------------------------------------
    url(r'^hafele/$', views.hafele, name='hafele'),
    url(r'^hafele/cylindrical-lever-handle-set$', views.hafele_cylindrical_lever_handle_set, name='hafele_cylindrical_lever_handle_set'),
    url(r'^hafele/lever-handle-set$', views.hafele_lever_handle_set, name='hafele_lever_handle_set'),
    url(r'^hafele/tubular-lever-handle-set$', views.hafele_tubular_lever_handle_set, name='hafele_tubular_lever_handle_set'),
    # -------------------------------------VIVA------------------------------------------
    url(r'^viva/$', views.viva, name='viva'),
    url(r'^viva/cylindrical-knob-set$', views.viva_cylindrical_knob_set, name='viva_cylindrical_knob_set'),
    url(r'^viva/hinge$', views.viva_hinge, name='viva_hinge'),
    url(r'^viva/hook-lock$', views.viva_hook_lock, name='viva_hook_lock'),
    url(r'^viva/tubular-lockset$', views.viva_tubular_lockset, name='viva_tubular_lockset'),
    # ----------------------------------------GRESET---------------------------------------------
    url(r'^greset/$', views.greset, name='greset'),
    url(r'^greset/cylindrical-lock$', views.greset_cylindrical_lock, name='greset_cylindrical_lock'),
    url(r'^greset/deadbolt-lock$', views.greset_deadbolt_lock, name='greset_deadbolt_lock'),
    url(r'^greset/handle-set$', views.greset_handle_set, name='greset_handle_set'),
    url(r'^greset/tubular-lever$', views.greset_tubular_lever, name='greset_tubular_lever'),
]

lajujaya/lajujaya/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^secret-admin-configure-page/', include(admin.site.urls)),
    url(r'^$', views.index, name="home"),
    url(r'^door/', include('door.urls', namespace="door")),
    url(r'^doorlock/', include('doorlock.urls', namespace='doorlock')),
    url(r'^enquiry/', include('enquiry.urls', namespace='enquiry')),
    url(r'^aluminium/', include('aluminium.urls', namespace='aluminium')),
    url(r'^kitchen-and-bathroom-accessories/', include('kitchen_bathroom_accessories.urls', namespace='kitchen_bathroom_accessories')),
    url(r'^others/', include('others.urls', namespace='others')),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^services$', views.services, name='services'),
    url(r'^FAQ$', views.faq, name='faq'),
    url(r'^(?P<filename>(robots.txt)|(humans.txt))$',
        views.home_files, name='home-files'),
]

if settings.DEBUG:
        urlpatterns += (url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
            }),
            url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.STATIC_ROOT,
            }))

lajujaya/doorlock/models.py
from django.db import models
import os
# Create your models here.

def path_and_rename(instance, filename):
    upload_to = 'doorlock/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.name:
        filename = '{}.{}'.format(instance.name, ext)
    else:
        pass
    # return the whole path to the file
    return os.path.join(upload_to, filename)

class DoorlockType(models.Model):
    type = models.CharField(max_length=100)

    def __str__(self):
        return self.type

class DoorlockCategory(models.Model):
    category = models.CharField(max_length=50)

    def __str__(self):
        return self.category

class DoorlockCatalog(models.Model):
    category = models.ForeignKey(DoorlockCategory)
    type = models.ForeignKey(DoorlockType)
    my_id = models.IntegerField(null=True)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to=path_and_rename)
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name

lajujaya/doorlock/views.py
from django.shortcuts import render
from .models import DoorlockCatalog
# my own function
from myfunction import page
# Create your views here.

def doorlock(request):
    return render(request, "doorlock/doorlock.html", {})

# ----------------------------------- ST GUCHI DOOR LOCK --------------------------------------
def st_guchi(request):
    context = {}
    return render(request, 'doorlock/st_guchi.html', context)

def st_guchi_accessories(request):
    st_guchi_accessories_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Accessories').order_by("my_id")
    context = {
        "st_guchi_accessories":page(st_guchi_accessories_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_accessories_page":st_guchi_accessories_catalog,
    }
    return render(request, 'doorlock/st_guchi_accessories.html', context)

def st_guchi_cylindrical_lever(request):
    st_guchi_cylindrical_lever_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Cylindrical Lever').order_by("my_id")
    context = {
        "st_guchi_cylindrical_lever":page(st_guchi_cylindrical_lever_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_cylindrical_lever_page":st_guchi_cylindrical_lever_catalog,
    }
    return render(request, 'doorlock/st_guchi_cylindrical_lever.html', context)

def st_guchi_cylindrical_lock(request):
    st_guchi_cylindrical_lock_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Cylindrical Lock').order_by("my_id")
    context = {
        "st_guchi_cylindrical_lock":page(st_guchi_cylindrical_lock_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_cylindrical_lock_page":st_guchi_cylindrical_lock_catalog,
    }
    return render(request, 'doorlock/st_guchi_cylindrical_lock.html', context)

def st_guchi_deadbolt_lock(request):
    st_guchi_deadbolt_lock_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Deadbolt Lock').order_by("my_id")
    context = {
        "st_guchi_deadbolt_lock":page(st_guchi_deadbolt_lock_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_deadbolt_lock_page":st_guchi_deadbolt_lock_catalog,
    }
    return render(request, 'doorlock/st_guchi_deadbolt_lock.html', context)

def st_guchi_door_closer(request):
    st_guchi_door_closer_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Door Closer').order_by("my_id")
    context = {
        "st_guchi_door_closer":page(st_guchi_door_closer_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_door_closer_page":st_guchi_door_closer_catalog,
    }
    return render(request, 'doorlock/st_guchi_door_closer.html', context)

def st_guchi_handle_set(request):
    st_guchi_handle_set_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Handle Set').order_by("my_id")
    context = {
        "st_guchi_handle_set":page(st_guchi_handle_set_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_handle_set_page":st_guchi_handle_set_catalog,
    }
    return render(request, 'doorlock/st_guchi_handle_set.html', context)

def st_guchi_lever_handle(request):
    st_guchi_lever_handle_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Lever Handle').order_by("my_id")
    context = {
        "st_guchi_lever_handle":page(st_guchi_lever_handle_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_lever_handle_page":st_guchi_lever_handle_catalog,
    }
    return render(request, 'doorlock/st_guchi_lever_handle.html', context)

def st_guchi_mortise_handle_set(request):
    st_guchi_mortise_handle_set_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Mortise Handle Set').order_by("my_id")
    context = {
        "st_guchi_mortise_handle_set":page(st_guchi_mortise_handle_set_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_mortise_handle_set_page":st_guchi_mortise_handle_set_catalog,
    }
    return render(request, 'doorlock/st_guchi_mortise_handle_set.html', context)

def st_guchi_mortise_lock(request):
    st_guchi_mortise_lock_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Mortise Lock').order_by("my_id")
    context = {
        "st_guchi_mortise_lock":page(st_guchi_mortise_lock_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_mortise_lock_page":st_guchi_mortise_lock_catalog,
    }
    return render(request, 'doorlock/st_guchi_mortise_lock.html', context)

def st_guchi_mortise_hook_lock(request):
    st_guchi_mortise_hook_lock_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Mortise Lock & Hook Lock').order_by("my_id")
    context = {
        "st_guchi_mortise_hook_lock":page(st_guchi_mortise_hook_lock_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_mortise_hook_lock_page":st_guchi_mortise_hook_lock_catalog,
    }
    return render(request, 'doorlock/st_guchi_mortise_hook_lock.html', context)

def st_guchi_pad_lock(request):
    st_guchi_pad_lock_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Pad Lock').order_by("my_id")
    context = {
        "st_guchi_pad_lock":page(st_guchi_pad_lock_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_pad_lock_page":st_guchi_pad_lock_catalog,
    }
    return render(request, 'doorlock/st_guchi_pad_lock.html', context)

def st_guchi_profile_cylinder(request):
    st_guchi_profile_cylinder_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Profile Cylinder').order_by("my_id")
    context = {
        "st_guchi_profile_cylinder":page(st_guchi_profile_cylinder_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_profile_cylinder_page":st_guchi_profile_cylinder_catalog,
    }
    return render(request, 'doorlock/st_guchi_profile_cylinder.html', context)

def st_guchi_pull_handle(request):
    st_guchi_pull_handle_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Pull Handle').order_by("my_id")
    context = {
        "st_guchi_pull_handle":page(st_guchi_pull_handle_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_pull_handle_page":st_guchi_pull_handle_catalog,
    }
    return render(request, 'doorlock/st_guchi_pull_handle.html', context)

def st_guchi_tubular_lever(request):
    st_guchi_tubular_lever_catalog = DoorlockCatalog.objects.filter(category__category="ST Guchi Door Lock", type__type='Tubular Lever').order_by("my_id")
    context = {
        "st_guchi_tubular_lever":page(st_guchi_tubular_lever_catalog), #name of this must be same as name for def contextElement!!!
        "st_guchi_tubular_lever_page":st_guchi_tubular_lever_catalog,
    }
    return render(request, 'doorlock/st_guchi_tubular_lever.html', context)

# ------------------------------- IKAROS -------------------------------------
def ikaros(request):
    context = {}
    return render(request, 'doorlock/ikaros.html', context)

def ikaros_cylindrical_lever(request):
    ikaros_cylindrical_lever_catalog = DoorlockCatalog.objects.filter(category__category="Ikaros Door Lock", type__type='Cylindrical Lever').order_by("my_id")
    context = {
        "ikaros_cylindrical_lever":page(ikaros_cylindrical_lever_catalog), #name of this must be same as name for def contextElement!!!
        "ikaros_cylindrical_lever_page":ikaros_cylindrical_lever_catalog,
    }
    return render(request, 'doorlock/ikaros_cylindrical_lever.html', context)

def ikaros_pad_lock(request):
    ikaros_pad_lock_catalog = DoorlockCatalog.objects.filter(category__category="Ikaros Door Lock", type__type='Pad Lock').order_by("my_id")
    context = {
        "ikaros_pad_lock":page(ikaros_pad_lock_catalog), #name of this must be same as name for def contextElement!!!
        "ikaros_pad_lock_page":ikaros_pad_lock_catalog,
    }
    return render(request, 'doorlock/ikaros_pad_lock.html', context)

# --------------------------------DIGITAL DOOR LOCK----------------------------------
def digital_doorlock(request):
    context = {}
    return render(request, 'doorlock/digital_doorlock.html', context)

def digital_doorlock_samsung(request):
    digital_doorlock_samsung_catalog = DoorlockCatalog.objects.filter(category__category="Digital Door Lock", type__type='Samsung').order_by("my_id")
    context = {
        "digital_doorlock_samsung":page(digital_doorlock_samsung_catalog), #name of this must be same as name for def contextElement!!!
        "digital_doorlock_samsung_page":digital_doorlock_samsung_catalog,
    }
    return render(request, 'doorlock/digital_doorlock_samsung.html', context)

def digital_doorlock_gateman(request):
    digital_doorlock_gateman_catalog = DoorlockCatalog.objects.filter(category__category="Digital Door Lock", type__type='Gateman').order_by("my_id")
    context = {
        "digital_doorlock_gateman":page(digital_doorlock_gateman_catalog), #name of this must be same as name for def contextElement!!!
        "digital_doorlock_gateman_page":digital_doorlock_gateman_catalog,
    }
    return render(request, 'doorlock/digital_doorlock_gateman.html', context)

# ---------------------------------HAFELE-------------------------------------------
def hafele(request):
    context = {}
    return render(request, 'doorlock/hafele.html', context)

def hafele_cylindrical_lever_handle_set(request):

lajujaya/doorlock/templates/doorlock/base_product_hafele.html
{% extends 'base_product.html' %}

{% block jumbotron %}
{% include 'jumbotron.html' with header="Hafele" %}
{% endblock %}

{% block contents %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2" id="sidebar-nav">
			<ul id="nav" class="nav nav-pills nav-stacked" data-spy="affix"> <!-- data-href == href of the #nav-top page's href -->
				<li><a href="{% url 'doorlock:hafele_cylindrical_lever_handle_set' %}" data-href="hafele_cylindrical_lever_handle_set">Cylindrical Lever Handle Set</a></li>
				<li><a href="{% url 'doorlock:hafele_lever_handle_set' %}" data-href="hafele_lever_handle_set">Lever Handle Set</a></li>
				<li><a href="{% url 'doorlock:hafele_tubular_lever_handle_set' %}" data-href="hafele_tubular_lever_handle_set">Tubular Lever Handle Set</a></li>
            </ul>
		</div>
		<div class="col-sm-9 col-md-10" id="content-col">
            <ul id="nav-top" class="nav nav-tabs" role="tablist" style="text-align: right; z-index: 1" data-spy="affix">
					<li style="float: left"><h4 class="nav-top-h4"></h4></li>
					<li role="presentation" class="active a"><a href="#solid_wooden_door" aria-controls="#solid_wooden_door" role="tab" data-toggle="tab">1</a></li>
					{% for i in "2345678"  %}
					<li role="presentation"><a href="#solid_wooden_door{{i}}" aria-controls="#solid_wooden_door{{i}}" role="tab" data-toggle="tab">{{i}}</a></li>
					{% endfor %}
            </ul>
    {% block hafele %}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

lajujaya/doorlock/templates/doorlock/base_product_viva.html
{% extends 'base_product.html' %}

{% block jumbotron %}
{% include 'jumbotron.html' with header="Viva" %}
{% endblock %}

{% block contents %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2" id="sidebar-nav">
			<ul id="nav" class="nav nav-pills nav-stacked" data-spy="affix"> <!-- data-href == href of the #nav-top page's href -->
				<li><a href="{% url 'doorlock:viva_cylindrical_knob_set' %}" data-href="viva_cylindrical_knob_set">Cylindrical Knob Set</a></li>
				<li><a href="{% url 'doorlock:viva_hinge' %}" data-href="viva_hinge">Hinge</a></li>
                <li><a href="{% url 'doorlock:viva_hook_lock' %}" data-href="viva_hook_lock">Hook Lock</a></li>
                <li><a href="{% url 'doorlock:viva_tubular_lockset' %}" data-href="viva_tubular_lockset">Tubular Lockset</a></li>
			</ul>
		</div>
		<div class="col-sm-9 col-md-10" id="content-col">
            <ul id="nav-top" class="nav nav-tabs" role="tablist" style="text-align: right; z-index: 1" data-spy="affix">
					<li style="float: left"><h4 class="nav-top-h4"></h4></li>
					<li role="presentation" class="active a"><a href="#solid_wooden_door" aria-controls="#solid_wooden_door" role="tab" data-toggle="tab">1</a></li>
					{% for i in "2345678"  %}
					<li role="presentation"><a href="#solid_wooden_door{{i}}" aria-controls="#solid_wooden_door{{i}}" role="tab" data-toggle="tab">{{i}}</a></li>
					{% endfor %}
            </ul>
    {% block viva %}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

lajujaya/doorlock/templates/doorlock/digital_doorlock.html
{% extends 'base_product.html' %}
{% load staticfiles %}

{% block title %}
<title>Digital Door Lock - Samsung & Gateman Digital Door Lock</title>
{% endblock %}

{% block jumbotron %}
{% include 'jumbotron.html' with header="Digital Door Lock" %}
{% endblock %}

{% block contents %}
<div class="container con-padding">
    <div class="row">
        <div class="col-sm-4 col-ms-6">
            <div class="table">
               <div class="table-cell">
                 <a href="{% url 'doorlock:digital_doorlock_samsung' %}">
                     <img class="img-thumbnail" src="{% static 'img/samsung digital doorlock.jpg' %}" alt="Samsung Digital Door Lock">
                 </a>
               </div>
            </div>
            <h4>Samsung Digital Door Lock</h4>
        </div>
        <div class="col-sm-4 col-ms-6">
            <div class="table">
               <div class="table-cell">
                 <a href="{% url 'doorlock:digital_doorlock_gateman' %}">
                     <img class="img-thumbnail" src="{% static 'img/gateman digital doorlock.jpg' %}" alt="Gateman Digital Door Lock">
                 </a>
               </div>
            </div>
            <h4>Gateman Digital Door Lock</h4>
        </div>
    </div>
</div>
{% endblock %}

lajujaya/doorlock/templates/doorlock/greset_handle_set.html
{% extends 'doorlock/base_product_greset.html' %}

{% block title %}
<title>Greset Handle Set | Door Lock in Johor Bahru (JB)</title>
{% endblock %}

{% block greset %}
<div class="tab-content">
    {% if greset_handle_set_page != greset_handle_set %}
    {% for d in greset_handle_set %}
        {% cycle "" "2" "3" "4" "5" "6" "7" "8" "9" as range silent %}
        {% if forloop.counter == 1 %}
        <div id="greset_handle_set{{range}}" class="tab-pane fade in active">
        {% else %}
        <div id="greset_handle_set{{range}}" class="tab-pane fade">
        {% endif %}
            {% for x in d %}
                {% if forloop.counter == 1 %}
	                <div class="row">
                {% endif %}
            {% include 'product_col.html' %}
            {% endfor %}
	                </div>
        </div>
    {% endfor %}
    {% else %}
        {% for x in greset_handle_set %}
        {% if forloop.counter == 1 %}
        <div id="greset_handle_set" class="tab-pane fade in active">
	        <div class="row">
        {% endif %}
            {% include 'product_col.html' %}
        {% endfor %}{% endif %}
	        </div>
        </div>
</div>
{% include 'contact_modal.html' %}
{% endblock %}

lajujaya/doorlock/templates/doorlock/greset_tubular_lever.html
{% extends 'doorlock/base_product_greset.html' %}

{% block title %}
<title>Greset Tubular Lever | Door Lock in Johor Bahru (JB)</title>
{% endblock %}

{% block greset %}
<div class="tab-content">
    {% if greset_tubular_lever_page != greset_tubular_lever %}
    {% for d in greset_tubular_lever %}
        {% cycle "" "2" "3" "4" "5" "6" "7" "8" "9" as range silent %}
        {% if forloop.counter == 1 %}
        <div id="greset_tubular_lever{{range}}" class="tab-pane fade in active">
        {% else %}
        <div id="greset_tubular_lever{{range}}" class="tab-pane fade">
        {% endif %}
            {% for x in d %}
                {% if forloop.counter == 1 %}
	                <div class="row">
                {% endif %}
            {% include 'product_col.html' %}
            {% endfor %}
	                </div>
        </div>
    {% endfor %}
    {% else %}
        {% for x in greset_tubular_lever %}
        {% if forloop.counter == 1 %}
        <div id="greset_tubular_lever" class="tab-pane fade in active">
	        <div class="row">
        {% endif %}
            {% include 'product_col.html' %}
        {% endfor %}{% endif %}
	        </div>
        </div>
</div>
{% include 'contact_modal.html' %}
{% endblock %}

lajujaya/doorlock/templates/doorlock/hafele.html
{% extends 'base_product.html' %}
{% load staticfiles %}

{% block title %}
<title>Hafele Door Lock - Cylindrical Lever Handle Set | Knob Lockset & Single Deadbolt</title>
{% endblock %}

{% block jumbotron %}
{% include 'jumbotron.html' with header="Hafele" %}
{% endblock %}

{% block contents %}
<div class="container con-padding">
    <div class="row">
        <div class="col-sm-4 col-ms-6">
            <div class="table">
               <div class="table-cell">
                 <a href="{% url 'doorlock:hafele_cylindrical_lever_handle_set' %}">
                     <img class="img-thumbnail" src="{% static 'img/hafele cylindrical lever handle set.jpg' %}" alt="Cylindrical Lever Handle Set">
                 </a>
               </div>
            </div>
            <h4>Cylindrical Lever Handle Set</h4>
        </div>
        <div class="col-sm-4 col-ms-6">
            <div class="table">
               <div class="table-cell">
                 <a href="{% url 'doorlock:hafele_lever_handle_set' %}">
                     <img class="img-thumbnail" src="{% static 'img/hafele lever handle set.jpg' %}" alt="Lever Handle Set">
                 </a>
               </div>
            </div>
            <h4>Lever Handle Set</h4>
        </div>
        <div class="col-sm-4 col-ms-6">
            <div class="table">
               <div class="table-cell">
                 <a href="{% url 'doorlock:hafele_tubular_lever_handle_set' %}">
                     <img class="img-thumbnail" src="{% static 'img/hafele tubular lever handle set.jpg' %}" alt="Tubular Lever Handle Set">
                 </a>
               </div>
            </div>
            <h4>Tubular Lever Handle Set</h4>
        </div>
    </div>
</div>
{% endblock %}

lajujaya/doorlock/templates/doorlock/ikaros.html
{% extends 'base_product.html' %}
{% load staticfiles %}

{% block title %}
<title>Ikaros Door Lock - Cylindrical Lever | Pad Lock</title>
{% endblock %}

{% block jumbotron %}
{% include 'jumbotron.html' with header="Ikaros" %}
{% endblock %}

{% block contents %}
<div class="container con-padding">
    <div class="row">
        <div class="col-sm-4 col-ms-6">
            <div class="table">
               <div class="table-cell">
                 <a href="{% url 'doorlock:ikaros_cylindrical_lever' %}">
                     <img class="img-thumbnail" src="{% static 'img/ikaros cylindrical lever.jpg' %}" alt="Cylindrical Lever">
                 </a>
               </div>
            </div>
            <h4>Cylindrical Lever</h4>
        </div>
        <div class="col-sm-4 col-ms-6">
            <div class="table">
               <div class="table-cell">
                 <a href="{% url 'doorlock:ikaros_pad_lock' %}">
                     <img class="img-thumbnail" src="{% static 'img/ikaros door lock.jpg' %}" alt="Pad Lock">
                 </a>
               </div>
            </div>
            <h4>Pad Lock</h4>
        </div>
    </div>
</div>
{% endblock %}