lajujaya/door/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.door, name='door'),
    url(r'^solid-wooden-door/$', views.solid_wooden_door, name="solid_wooden_door"),
    url(r'^firedoor/$', views.firedoor, name="firedoor"),
    url(r'^MPC-design-door/$', views.MPC_design_door, name="MPC_design_door"),
]

lajujaya/lajujaya/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^secret-admin-configure-page/', include(admin.site.urls)),
    url(r'^$', views.index, name="home"),
    url(r'^door/', include('door.urls', namespace="door")),
    url(r'^doorlock/', include('doorlock.urls', namespace='doorlock')),
    url(r'^enquiry/', include('enquiry.urls', namespace='enquiry')),
    url(r'^aluminium/', include('aluminium.urls', namespace='aluminium')),
    url(r'^kitchen-and-bathroom-accessories/', include('kitchen_bathroom_accessories.urls', namespace='kitchen_bathroom_accessories')),
    url(r'^others/', include('others.urls', namespace='others')),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^services$', views.services, name='services'),
    url(r'^FAQ$', views.faq, name='faq'),
    url(r'^(?P<filename>(robots.txt)|(humans.txt))$',
        views.home_files, name='home-files'),
]

if settings.DEBUG:
        urlpatterns += (url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
            }),
            url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.STATIC_ROOT,
            }))

lajujaya/others/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.others, name='others'),
    url(r'^staircase$', views.others_staircase, name='others_staircase'),
    url(r'^wooden-window$', views.others_wooden_window, name='others_wooden_window'),
    url(r'^autogate-system$', views.others_autogate_system, name='others_autogate_system'),
    url(r'^hardware-misc$', views.others_hardware_misc, name='others_hardware_misc'),
]

lajujaya/others/models.py
from django.db import models
import os
# Create your models here.

def path_and_rename(instance, filename):
    upload_to = 'others/'
    ext = filename.split('.')[-1]
    ori_name = filename.split('.')[0]
    # get filename
    if instance.name:
        filename = '{}.{}'.format(instance.name, ext)
    else:
        pass
    # return the whole path to the file
    return os.path.join(upload_to, filename)

class OthersType(models.Model):
    type = models.CharField(max_length=100)

    def __str__(self):
        return self.type

class OthersCatalog(models.Model):
    type = models.ForeignKey(OthersType)
    my_id = models.IntegerField(null=True)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to=path_and_rename)
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name

class Carosel(models.Model):
    page = models.IntegerField()
    image = models.ImageField(upload_to=path_and_rename)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

lajujaya/others/views.py
from django.shortcuts import render
from .models import OthersCatalog
from myfunction import page
# Create your views here.

def others(request):
    context = {}
    return render(request, 'others/others.html', context)

def others_staircase(request):
    others_staircase_catalog = OthersCatalog.objects.filter(type__type="Staircase").order_by("my_id")
    context = {
        "others_staircase":page(others_staircase_catalog), #name of this must be same as name for def contextElement!!!
        "others_staircase_page":others_staircase_catalog,
    }
    return render(request, 'others/others_staircase.html', context)

def others_wooden_window(request):
    others_wooden_window_catalog = OthersCatalog.objects.filter(type__type="Wooden Window").order_by("my_id")
    context = {
        "others_wooden_window":page(others_wooden_window_catalog), #name of this must be same as name for def contextElement!!!
        "others_wooden_window_page":others_wooden_window_catalog,
    }
    return render(request, 'others/others_wooden_window.html', context)

def others_autogate_system(request):
    others_autogate_system_catalog = OthersCatalog.objects.filter(type__type="Autogate System").order_by("my_id")
    context = {
        "others_autogate_system":page(others_autogate_system_catalog), #name of this must be same as name for def contextElement!!!
        "others_autogate_system_page":others_autogate_system_catalog,
    }
    return render(request, 'others/others_autogate_system.html', context)

def others_hardware_misc(request):
    others_hardware_misc_catalog = OthersCatalog.objects.filter(type__type="Hardware Misc").order_by("my_id")
    context = {
        "others_hardware_misc":page(others_hardware_misc_catalog), #name of this must be same as name for def contextElement!!!
        "others_hardware_misc_page":others_hardware_misc_catalog,
    }
    return render(request, 'others/others_hardware_misc.html', context)

lajujaya/others/templates/others/base_product_others.html
{% extends 'base_product.html' %}

{% block jumbotron %}
{% include 'jumbotron.html' with header="Other Products" %}
{% endblock %}

{% block contents %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2" id="sidebar-nav">
			<ul id="nav" class="nav nav-pills nav-stacked" data-spy="affix"> <!-- data-href == href of the #nav-top page's href -->
				<li><a href="{% url 'others:others_staircase' %}" data-href="others_staircase">Staircase</a></li>
				<li><a href="{% url 'others:others_wooden_window' %}" data-href="others_wooden_window">Wooden Window</a></li>
                <li><a href="{% url 'others:others_autogate_system' %}" data-href="others_autogate_system">Autogate System</a></li>
                <li><a href="{% url 'others:others_hardware_misc' %}" data-href="others_hardware_misc">Hardware Misc</a></li>
			</ul>
		</div>
		<div class="col-sm-9 col-md-10" id="content-col">
            <ul id="nav-top" class="nav nav-tabs" role="tablist" style="text-align: right; z-index: 1" data-spy="affix">
					<li style="float: left"><h4 class="nav-top-h4"></h4></li>
					<li role="presentation" class="active a"><a href="#solid_wooden_door" aria-controls="#solid_wooden_door" role="tab" data-toggle="tab">1</a></li>
					{% for i in "2345678"  %}
					<li role="presentation"><a href="#solid_wooden_door{{i}}" aria-controls="#solid_wooden_door{{i}}" role="tab" data-toggle="tab">{{i}}</a></li>
					{% endfor %}
            </ul>
    {% block others %}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

lajujaya/others/templates/others/others.html
{% extends 'base_product.html' %}
{% load staticfiles %}

{% block title %}
<title>Others - Staircase | Autogate System | Shower Screen | Hardware Misc</title>
{% endblock %}

{% block jumbotron %}
{% include 'jumbotron.html' with header="Other Products" %}
{% endblock %}

{% block contents %}
<div class="container con-padding">
    <div class="row">
        <div class="col-sm-4 col-ms-6">
            <div class="table">
               <div class="table-cell">
                 <a href="{% url 'others:others_staircase' %}">
                     <img class="img-thumbnail" src="{% static 'img/staircase.jpg' %}" alt="Staircase">
                 </a>
               </div>
            </div>
            <h4>Staircase</h4>
        </div>
        <div class="col-sm-4 col-ms-6">
            <div class="table">
               <div class="table-cell">
                 <a href="{% url 'others:others_wooden_window' %}">
                     <img class="img-thumbnail" src="{% static 'img/wooden window.jpg' %}" alt="Wooden Window">
                 </a>
               </div>
            </div>
            <h4>Wooden Window</h4>
        </div>
        <div class="col-sm-4 col-ms-6">
            <div class="table">
               <div class="table-cell">
                 <a href="{% url 'others:others_autogate_system' %}">
                     <img class="img-thumbnail" src="{% static 'img/autogate.jpg' %}" alt="Autogate System">
                 </a>
               </div>
            </div>
            <h4>Autogate System</h4>
        </div>
        <div class="col-sm-4 col-ms-6">
            <div class="table">
               <div class="table-cell">
                 <a href="{% url 'others:others_hardware_misc' %}">
                     <img class="img-thumbnail" src="{% static 'img/hardware misc.jpg' %}" alt="Hardware Misc">
                 </a>
               </div>
            </div>
            <h4>Hardware Misc</h4>
        </div>
    </div>
</div>
{% endblock %}

lajujaya/others/templates/others/others_autogate_system.html
{% extends 'others/base_product_others.html' %}

{% block title %}
<title>Autogate System | Autogate System in Johor Bahru (JB)</title>
{% endblock %}

{% block others %}
<div class="tab-content">
    {% if others_autogate_system_page != others_autogate_system %}
    {% for d in others_autogate_system %}
        {% cycle "" "2" "3" "4" "5" "6" "7" "8" "9" as range silent %}
        {% if forloop.counter == 1 %}
        <div id="others_autogate_system{{range}}" class="tab-pane fade in active">
        {% else %}
        <div id="others_autogate_system{{range}}" class="tab-pane fade">
        {% endif %}
            {% for x in d %}
                {% if forloop.counter == 1 %}
	                <div class="row">
                {% endif %}
            {% include 'product_col.html' %}
            {% endfor %}
	                </div>
        </div>
    {% endfor %}
    {% else %}
        {% for x in others_autogate_system %}
        {% if forloop.counter == 1 %}
        <div id="others_autogate_system" class="tab-pane fade in active">
	        <div class="row">
        {% endif %}
            {% include 'product_col.html' %}
        {% endfor %}{% endif %}
	        </div>
        </div>
</div>
{% include 'contact_modal.html' %}
{% endblock %}

lajujaya/others/templates/others/others_hardware_misc.html
{% extends 'others/base_product_others.html' %}

{% block title %}
<title>Hardware Misc | Hardware Misc in Johor Bahru (JB)</title>
{% endblock %}

{% block others %}
<div class="tab-content">
    {% if others_hardware_misc_page != others_hardware_misc %}
    {% for d in others_hardware_misc %}
        {% cycle "" "2" "3" "4" "5" "6" "7" "8" "9" as range silent %}
        {% if forloop.counter == 1 %}
        <div id="others_hardware_misc{{range}}" class="tab-pane fade in active">
        {% else %}
        <div id="others_hardware_misc{{range}}" class="tab-pane fade">
        {% endif %}
            {% for x in d %}
                {% if forloop.counter == 1 %}
	                <div class="row">
                {% endif %}
            {% include 'product_col.html' %}
            {% endfor %}
	                </div>
        </div>
    {% endfor %}
    {% else %}
        {% for x in others_hardware_misc %}
        {% if forloop.counter == 1 %}
        <div id="others_hardware_misc" class="tab-pane fade in active">
	        <div class="row">
        {% endif %}
            {% include 'product_col.html' %}
        {% endfor %}{% endif %}
	        </div>
        </div>
</div>
{% include 'contact_modal.html' %}
{% endblock %}

lajujaya/others/templates/others/others_staircase.html
{% extends 'others/base_product_others.html' %}

{% block title %}
<title>Staircase | Home's Staircase in Johor Bahru (JB)</title>
{% endblock %}

{% block others %}
<div class="tab-content">
    {% if others_staircase_page != others_staircase %}
    {% for d in others_staircase %}
        {% cycle "" "2" "3" "4" "5" "6" "7" "8" "9" as range silent %}
        {% if forloop.counter == 1 %}
        <div id="others_staircase{{range}}" class="tab-pane fade in active">
        {% else %}
        <div id="others_staircase{{range}}" class="tab-pane fade">
        {% endif %}
            {% for x in d %}
                {% if forloop.counter == 1 %}
	                <div class="row">
                {% endif %}
            {% include 'product_col.html' %}
            {% endfor %}
	                </div>
        </div>
    {% endfor %}
    {% else %}
        {% for x in others_staircase %}
        {% if forloop.counter == 1 %}
        <div id="others_staircase" class="tab-pane fade in active">
	        <div class="row">
        {% endif %}
            {% include 'product_col.html' %}
        {% endfor %}{% endif %}
	        </div>
        </div>
</div>
{% include 'contact_modal.html' %}
{% endblock %}

lajujaya/others/templates/others/others_wooden_window.html
{% extends 'others/base_product_others.html' %}

{% block title %}
<title>Wooden Window | Wooden Window in Johor Bahru (JB)</title>
{% endblock %}

{% block others %}
<div class="tab-content">
    {% if others_wooden_window_page != others_wooden_window %}
    {% for d in others_wooden_window %}
        {% cycle "" "2" "3" "4" "5" "6" "7" "8" "9" as range silent %}
        {% if forloop.counter == 1 %}
        <div id="others_wooden_window{{range}}" class="tab-pane fade in active">
        {% else %}
        <div id="others_wooden_window{{range}}" class="tab-pane fade">
        {% endif %}
            {% for x in d %}
                {% if forloop.counter == 1 %}
	                <div class="row">
                {% endif %}
            {% include 'product_col.html' %}
            {% endfor %}
	                </div>
        </div>
    {% endfor %}
    {% else %}
        {% for x in others_wooden_window %}
        {% if forloop.counter == 1 %}
        <div id="others_wooden_window" class="tab-pane fade in active">
	        <div class="row">
        {% endif %}
            {% include 'product_col.html' %}
        {% endfor %}{% endif %}
	        </div>
        </div>
</div>
{% include 'contact_modal.html' %}
{% endblock %}