lajujaya/aluminium/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.aluminium, name='aluminium'),
    url(r'^aluminium-door$', views.aluminium_door, name="aluminium_door"),
    url(r'^aluminium-cabinet$', views.aluminium_cabinet, name="aluminium_cabinet"),
    url(r'^shower-screen', views.aluminium_shower_screen, name='shower_screen'),
]

lajujaya/door/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.door, name='door'),
    url(r'^solid-wooden-door/$', views.solid_wooden_door, name="solid_wooden_door"),
    url(r'^firedoor/$', views.firedoor, name="firedoor"),
    url(r'^MPC-design-door/$', views.MPC_design_door, name="MPC_design_door"),
]

lajujaya/kitchen_bathroom_accessories/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.kitchen_bathroom_accessories, name='kitchen_bathroom_accessories'),
    url(r'^sink/$', views.sink, name="sink"),
    url(r'^kitchen-accessories/$', views.kitchen_accessories, name="kitchen_accessories"),
    url(r'^bathroom-accessories/$', views.bathroom_accessories, name="bathroom_accessories"),
    url(r'^water-tap/$', views.water_tap, name="water_tap"),
]

lajujaya/lajujaya/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^secret-admin-configure-page/', include(admin.site.urls)),
    url(r'^$', views.index, name="home"),
    url(r'^door/', include('door.urls', namespace="door")),
    url(r'^doorlock/', include('doorlock.urls', namespace='doorlock')),
    url(r'^enquiry/', include('enquiry.urls', namespace='enquiry')),
    url(r'^aluminium/', include('aluminium.urls', namespace='aluminium')),
    url(r'^kitchen-and-bathroom-accessories/', include('kitchen_bathroom_accessories.urls', namespace='kitchen_bathroom_accessories')),
    url(r'^others/', include('others.urls', namespace='others')),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^services$', views.services, name='services'),
    url(r'^FAQ$', views.faq, name='faq'),
    url(r'^(?P<filename>(robots.txt)|(humans.txt))$',
        views.home_files, name='home-files'),
]

if settings.DEBUG:
        urlpatterns += (url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
            }),
            url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.STATIC_ROOT,
            }))

lajujaya/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
{% spaceless %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    {% block meta %}{% endblock %}
    <meta property="og:url" content="http://lajujayatrd.com" />
	<meta property="og:type" content="website" />
	<meta property="og:title" content="Laju Jaya Trading | Johor Bahru" />
	<meta property="og:description" content="Door, Digital Door Lock, Door Lock, Kitchen & Bathroom Accessories, Bathroom Bi-Fold Door, Aluminium Cabinet and More in Johor Bahru >> Check out more !!" />
	<meta property="og:image" content="http://lajujayatrd.com/static/img/cover1.jpg" />
    <meta property="fb:admins" content="100000426900931" />
    <meta name="author" content="CH~">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    {% block title %}{% endblock %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap_ms.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.offcanvas.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/navbar.css' %}" rel="stylesheet">
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">

    {% block css %}{% endblock %}
  </head>

  <body>
<div class="wrapper">
  <!-- --------------navbar----------- -->
    {% include 'navbar.html' with chinese="利竹贸易"%}

	{% block cover %}{% endblock %}{% block content %}{% endblock %}

<!-- -------------ScrollToPageTop----------- -->
<a href="#" class="scrollToTop"><span class="glyphicon glyphicon-chevron-up"></span></a>

<footer>
{% include 'footer.html' %}
</footer>
</div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/navbar.js' %}"></script>
    <script src="{% static 'js/cover.js' %}"></script>
    <script src="{% static 'js/bootstrap.offcanvas.min.js' %}"></script>
    {% block js %}{% endblock %}
  </body>
</html>
{% endspaceless %}

lajujaya/templates/contact_form.html
{% load crispy_forms_tags %}
<form role="form" method="post" id="modal-form">{% csrf_token %}
    {{form | crispy}}
</form>

lajujaya/templates/contact_us_page_form.html
{% load crispy_forms_tags %}
<form role="form" method="post" id="contact-form">{% csrf_token %}
    {{form | crispy}}
</form>

lajujaya/templates/faq.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
<title>FAQ | Laju Jaya Trading - Door Shop in Johor Bahru(JB)</title>
{% endblock %}

{% block css %}
<link href="{% static 'css/faq.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="jumbotron cover-faq">
    <h1 class="wow bounceIn">Frequently Asked Questions</h1>
</div>
<div class="container con">
    <div class="row">
        <h1>Sorry, this page is now not available, please come again later !</h1>
    </div>
</div>
{% endblock %}

lajujaya/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block meta %}
<meta name="description" content="Located in Johor Bahru, we sell door, door lock, digital door lock, kitchen & bathroom accessories
and More with LOWEST PRICE and ATTRACTIVE OFFERS!">
{% endblock %}

{% block title %}
<title>Laju Jaya Trading - Door, Door Lock & More in Johor Bahru</title>
{% endblock %}

{% block cover %}
<div id="owl-demo" class="owl-carousel owl-theme">
    {% for item in carosel %}
    {% if forloop.counter == 1 %}
      <div class="item con-bg1" style="background-image: url({{ item.image.url }});">
        <div class="table">
              <div class="table-cell">
                <h1 class="wow bounceInLeft" data-wow-duration="2s">{{ item.name }}</h1>
              </div>
          </div>
      </div>
    {% else %}
      <div class="item con-bg1" style="background-image: url({{ item.image.url }});">
          <div class="table">
              <div class="table-cell">
                <h1>{{ item.name }}</h1>
              </div>
          </div>
      </div>
    {% endif %}
    {% endfor %}
</div>

<div class="container con">
    <div class="row row-product">
        <h2 class="wow bounce" data-wow-duration="2s">We specialized in various category, Inside & Outside of your house  <span class="fa fa-home icon"></span></h2>
        <div class="col-sm-4 col-ms-6 wow fadeInUp" data-wow-duration="1s">
            <div class="hovereffect">
                <img class="img-responsive" src="{% static 'img/cover-door.jpg' %}" alt="Door">
                <div class="overlay">
                   <h2>Doors</h2>
                   <a class="info" href="{% url 'door:door' %}">More Doors >></a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 text">
                    <h4>Doors</h4>
                    <a href="{% url 'door:door' %}" class="btn btn-lg btn-default">More Doors >></a>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-ms-6 wow fadeInUp" data-wow-duration="1s">
            <div class="hovereffect">
                <img class="img-responsive" src="{% static 'img/digital_lock2.jpg' %}" alt="Digital Door Lock">
                <div class="overlay">
                   <h2>Digital Door Locks</h2>
                   <a class="info" href="{% url 'doorlock:digital_doorlock' %}">More Digital Door Locks >></a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 text">
                    <h4>Digital Door Locks</h4>
                    <a href="{% url 'doorlock:digital_doorlock' %}" class="btn btn-lg btn-default">More Digital Locks >></a>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-ms-6 wow fadeInUp" data-wow-duration="1s">
            <div class="hovereffect">
                <img class="img-responsive" src="{% static 'img/cover-door-lock.jpg' %}" alt="Door Lock">
                <div class="overlay">
                   <h2>Door Locks</h2>
                   <a class="info" href="{% url 'doorlock:doorlock' %}">More Door Locks >></a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 text">
                    <h4>Door Locks</h4>
                    <a href="{% url 'doorlock:doorlock' %}" class="btn btn-lg btn-default">More Door Locks >></a>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-ms-6 wow fadeInUp" data-wow-duration="1s">
            <div class="hovereffect">
                <img class="img-responsive" src="{% static 'img/cover-aluminium.jpg' %}" alt="Aluminium Products">
                <div class="overlay">
                   <h2>Aluminium Products</h2>
                   <a class="info" href="{% url 'aluminium:aluminium' %}">More Aluminium Products >></a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 text">
                    <h4>Aluminium Products</h4>
                    <a href="{% url 'aluminium:aluminium' %}" class="btn btn-lg btn-default">More Products >></a>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-ms-6 wow fadeInUp" data-wow-duration="1s">
            <div class="hovereffect">
                <img class="img-responsive" src="{% static 'img/cover-kitchen.jpg' %}" alt="Bathroom & Kitchen Accessories">
                <div class="overlay">
                   <h2>Kitchen & Bathroom Accessories</h2>
                   <a class="info" href="{% url 'kitchen_bathroom_accessories:kitchen_bathroom_accessories' %}">See More >></a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 text">
                    <h4>Kitchen & Bathroom Accessories</h4>
                    <a href="{% url 'kitchen_bathroom_accessories:kitchen_bathroom_accessories' %}" class="btn btn-lg btn-default">See More >></a>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-ms-6 wow fadeInUp" data-wow-duration="1s">
            <div class="hovereffect">
                <img class="img-responsive" src="{% static 'img/cover-others.jpg' %}" alt="Other Products">
                <div class="overlay">
                   <h2>Other Products</h2>
                   <a class="info" href="{% url 'others:others' %}">More Other Products >></a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 text">
                    <h4>Other Products</h4>
                    <a href="{% url 'others:others' %}" class="btn btn-lg btn-default">More Other Products >></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="jumbotron cover-digital">
    <h1 class="wow bounceIn" data-wow-duration="1s">Digital Door Lock</h1>
</div>
<div class="container con">
    <div class="row row-product" id="digital">
        <div class="col-xs-12 text" style="padding-top: 0;padding-bottom: 10px;">
            <h4 style="color:#fcac45;padding-top:20px;font-weight:bold;">Advantages of Digital Door Lock  <span class="fa fa-share" style="padding-left:20px;color:#fcac45;"></span></h4>
            <div class="line" style="margin-top:0;border-top: 4px solid rgba(252, 172, 69, 0.48);"></div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="list wow fadeInLeft">
                        <p><span class="fa fa-check-square-o"></span>Various ways to open a door - finger print, user access code, key tag and mechanical override key</p>
                    </div>
                    <div class="list wow fadeInLeft">
                        <p><span class="fa fa-check-square-o"></span>Anti-hacking encryption protocol</p>
                    </div>
                    <div class="list wow fadeInLeft">
                        <p><span class="fa fa-check-square-o"></span>Unprecedented design with modern style</p>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="list wow fadeInLeft">
                        <p><span class="fa fa-check-square-o"></span>Robust structural-design</p>
                    </div>
                    <div class="list wow fadeInLeft">
                        <p><span class="fa fa-check-square-o"></span>Long Battery Life Span</p>
                    </div>
                </div>
            </div>
            <hr class="featurette-divider" style="margin-top: 60px;border-top-color:#fcac45;">
            <h4 style="color:#fcac45;padding-top:40px;font-weight:bold;" >We even provides you with  <span class="fa fa-share" style="padding-left:20px;color:#fcac45;"></span></h4>
            <div class="line" style="margin-top:0;border-top: 4px solid rgba(252, 172, 69, 0.48);"></div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="list wow bounceIn">
                        <p><span class="fa fa-check-circle"></span>1 year Warranty</p>
                    </div>
                    <div class="list wow bounceIn" data-wow-delay="0.2s">
                        <p><span class="fa fa-check-circle"></span>Installation included</p>
                    </div>
                    <div class="list wow bounceIn" data-wow-delay="0.4s">
                        <p><span class="fa fa-check-circle"></span>On phone & On site support</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="hovereffect wow fadeInUp">
                <img class="img-responsive" src="{% static 'img/digital_lock2.jpg' %}" alt="Samsung Digital Lock" style="width: auto;height:380px;">
                <div class="overlay">
                   <h2>Samsung</h2>
                   <a class="info" href="#">Samsung Digital Lock</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="hovereffect wow fadeInUp">
                <img class="img-responsive" src="{% static 'img/digital_lock1.jpg' %}" alt="Gateman Digital Lock" style="width: auto;height:380px;">
                <div class="overlay">
                   <h2>GateMan</h2>
                   <a class="info" href="#">Gateman Digital Lock</a>
                </div>
            </div>
        </div>
        <div class="col-xs-12 wow fadeInUp">
            <a href="{% url 'doorlock:digital_doorlock' %}" class="btn btn-default btn-lg btn-self">See More  >></a>
        </div>
    </div>
</div>
<div class="jumbotron cover-service">
    <h1 class="wow bounceIn">Professional Services</h1>
</div>
<div class="container con">
    <div class="well well-sm well-orange wow fadeInDown">
        <h4>What We Offer</h4>
    </div>
    <div class="row row-product">
        <div class="col-sm-4 col-ms-6 wow fadeInUp" data-sr='enter left,move 30px,reset,over 1s'>
            <span class="fa fa-paint-brush icon"></span>
            <h4 class="text">Door Varnishing / Painting</h4>
        </div>
        <div class="col-sm-4 col-ms-6 wow bounceInUp" data-wow-delay="0.2s" data-sr='enter bottom,move 30px,reset,over 1s,wait 0.2s'>
            <span class="fa fa-cog fa-spin icon"></span>
            <h4 class="text">Digital Door Lock Installation</h4>
        </div>
        <div class="col-sm-4 col-ms-6 wow fadeInUp" data-wow-delay="0.4s" data-sr='enter right,move 30px,reset,over 1s,wait 0.4s'>
            <span class="fa fa-wrench icon"></span>
            <h4 class="text">Door & Door Lock Installation</h4>
        </div>
    </div>
</div>
<div class="jumbotron cover-about">
    <h1 class="wow flipInY">About Us</h1>
</div>
<div class="colour">
    <div class="container">
        <div class="box wow fadeInUpBig">
            <div class="well about">
                <p><span class="fa fa-quote-left fa-2x fa-pull-left fa-border"></span>
                    Laju Jaya Trading is a company which specialized in, construction works, design & renovation,
                    door, door lock & accessories, digital Door lock, hardware, sanitary ware, bathroom & kitchen
                    accessories and furniture.</p><p></p>
                <p>Our company team has extensive experience and professional skills that ready to serve all of our
                    customers. Besides that, our professional company team will provide the professional advices and
                    opinions to solve your problem as well.  Hence, we have a group of loyal customers since the first
                    day our company establishes until today.</p><p></p>
                <p>
                    We believe the high quality products are the main factor to maintain and get trusted from customers,
                    that why we insist with this aim and it never change. We will fulfill your desire and satisfy with our
                    services. So, our target now is increase our sales marketing and expands our business network to nationwide.
                    <span class="fa fa-quote-right fa-2x fa-pull-right fa-border"></span>
                </p>
                <p></p><p></p>
            </div>
        </div>
    </div>
</div>
<div class="container con contact">
    <h2 class="wow fadeInUp"><span class="text-muted">FEEL FREE TO</span> CONTACT US</h2>
    <div class="line">
        <hr>
    </div>
    <div class="row row-product">
        <div class="col-sm-6 flex" style="text-align: left">
            <h3 class="info wow fadeInUp">Contact Info   <span class="fa fa-phone-square icon-phone fa-2x"></span></h3>
            <p class="wow fadeInUp" data-wow-delay="0.2s"><span class="fa fa-building fa-fw icon-contact"></span>Laju Jaya Trading</p>
            <p class="wow fadeInUp" data-wow-delay="0.4s"><span class="fa fa-map-marker fa-fw icon-contact"></span>25, Jalan Setia 9/17, Taman Setia Indah, 81100 Johor Bahru, Johor, Malaysia.</p>
            <p class="wow fadeInUp" data-wow-delay="0.6s"><span class="fa fa-fax fa-fw icon-contact"></span>+607-3596775</p>
            <p class="wow fadeInUp" data-wow-delay="0.8s"><span class="fa fa-envelope fa-fw icon-contact"></span>lajujayatrd@gmail.com</p>
            <p class="wow fadeInUp" data-wow-delay="1s"><span class="fa fa-mobile fa-fw icon-contact"></span>+6016-7185081, +6016-7155081</p>
        </div>
        <div class="col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
            <div id="googleMap" style="width:auto;height:280px;"></div>
        </div>
    </div>
</div>

{% endblock %}

lajujaya/templates/navbar.html
<nav class="navbar navbar-default navbar-fixed-top navbar-at-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle offcanvas-toggle" data-toggle="offcanvas" data-target="#js-bootstrap-offcanvas">
            <span class="sr-only">Toggle navigation</span>
            <span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </span>
        </button>
      <a class="navbar-brand" href="{% url 'home' %}">Laju Jaya Trading <span class="manderin">{{ chinese }}</span></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <!-- Push Menu Left -->
    <div class="navbar-offcanvas navbar-offcanvas-touch" id="js-bootstrap-offcanvas">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Products <span class="caret"></span></a>
          <ul class="dropdown-menu row no-shadow" role="menu" style="height:auto;background-color: white">
				<li class="col-sm-3">
					<ul>
						<li class="dropdown-header"><a href="{% url 'door:door' %}">Doors</a></li>
						<li><a href="{% url 'door:solid_wooden_door' %}">Solid Wooden Door</a></li>
						<li><a href="{% url 'door:firedoor' %}">Fire Door</a></li>
						<li><a href="{% url 'door:MPC_design_door' %}">MPC Design Door</a></li>
						<li class="divider"></li>
						<li class="dropdown-header"><a href="{% url 'aluminium:aluminium' %}">Aluminium Products</a></li>
						<li><a href="{% url 'aluminium:aluminium_cabinet' %}">Aluminium Cabinet</a></li>
						<li><a href="{% url 'aluminium:aluminium_door' %}">Aluminium Door</a></li>
						<li><a href="{% url 'aluminium:shower_screen' %}">Shower Screen</a></li>
                      <li class="divider"></li>
                      <li class="dropdown-header header-inline"><a href="{% url 'kitchen_bathroom_accessories:kitchen_bathroom_accessories' %}">Kitchen & Bathroom Accessories</a></li>
						<li><a href="{% url 'kitchen_bathroom_accessories:sink' %}">Sink</a></li>
						<li><a href="{% url 'kitchen_bathroom_accessories:kitchen_accessories' %}">Kitchen Accessories</a></li>
						<li><a href="{% url 'kitchen_bathroom_accessories:bathroom_accessories' %}">Bathroom Accessories</a></li>
						<li><a href="{% url 'kitchen_bathroom_accessories:water_tap' %}">Water Tap</a></li>
                      <li class="divider"></li>
                      <li class="dropdown-header"><a href="{% url 'doorlock:ikaros' %}">Ikaros Door Lock</a></li>
						<li><a href="{% url 'doorlock:ikaros_cylindrical_lever' %}">Cylindrical Level</a></li>
						<li><a href="{% url 'doorlock:ikaros_pad_lock' %}">Pad Lock</a></li>

					</ul>
				</li>
				<li class="col-sm-3">
					<ul>
                      <li class="dropdown-header"><a href="{% url 'doorlock:digital_doorlock' %}">Digital Door Lock  <span class="glyphicon glyphicon-fire icon-fire" style="padding-left: 15px"></span></a></li>
						<li><a href="{% url 'doorlock:digital_doorlock_samsung' %}">Samsung</a></li>
						<li><a href="{% url 'doorlock:digital_doorlock_gateman' %}">Gateman</a></li>
						<li class="divider"></li>
						<li class="dropdown-header"><a href="{% url 'doorlock:hafele' %}">Hafele Door Lock</a></li>
                      <li class="hafele-inline"><a href="{% url 'doorlock:hafele_cylindrical_lever_handle_set' %}">Cylindrical Lever Handle Set</a></li>
                      <li><a href="{% url 'doorlock:hafele_lever_handle_set' %}">Lever Handle Set</a></li>
                      <li class="hafele-inline"><a href="{% url 'doorlock:hafele_tubular_lever_handle_set' %}">Tubular Lever Handle Set</a></li>
						<li class="divider"></li>
						<li class="dropdown-header"><a href="{% url 'doorlock:viva' %}">Viva Door Lock</a></li>
                      <li><a href="{% url 'doorlock:viva_cylindrical_knob_set' %}">Cylindrical Knob Set</a></li>
                      <li><a href="{% url 'doorlock:viva_hinge' %}">Hinge</a></li>
                      <li><a href="{% url 'doorlock:viva_hook_lock' %}">Hook Lock</a></li>
                      <li><a href="{% url 'doorlock:viva_tubular_lockset' %}">Tubular Lockset</a></li>
					</ul>
				</li>
				<li class="col-sm-3">
					<ul>
                      <li class="dropdown-header"><a href="{% url 'doorlock:st_guchi' %}">ST Guchi Door Lock</a></li>
                      <li><a href="{% url 'doorlock:st_guchi_accessories' %}">Accessories</a></li>
                      <li><a href="{% url 'doorlock:st_guchi_cylindrical_lever' %}">Cylindrical Level</a></li>
                      <li><a href="{% url 'doorlock:st_guchi_cylindrical_lock' %}">Cylindrical Lock</a></li>
                      <li><a href="{% url 'doorlock:st_guchi_deadbolt_lock' %}">Deadbolt Lock</a></li>
                      <li><a href="{% url 'doorlock:st_guchi_door_closer' %}">Door Closer</a></li>
                      <li><a href="{% url 'doorlock:st_guchi_handle_set' %}">Handle Set</a></li>
                      <li><a href="{% url 'doorlock:st_guchi_lever_handle' %}">Lever Handle</a></li>
                      <li><a href="{% url 'doorlock:st_guchi_mortise_lock' %}">Mortise Lock</a></li>
                      <li><a href="{% url 'doorlock:st_guchi_mortise_handle_set' %}">Mortise Handle Set</a></li>
                      <li class="st_guchi-inline"><a href="{% url 'doorlock:st_guchi_mortise_hook_lock' %}">Mortise Lock & Hook Lock</a></li>
                      <li><a href="{% url 'doorlock:st_guchi_pad_lock' %}">Pad Lock</a></li>
                      <li><a href="{% url 'doorlock:st_guchi_profile_cylinder' %}">Profile Cylinder</a></li>
                      <li><a href="{% url 'doorlock:st_guchi_pull_handle' %}">Pull Handle</a></li>
					  <li><a href="{% url 'doorlock:st_guchi_tubular_lever' %}">Tubular Lever</a></li>
					</ul>
				</li>
				<li class="col-sm-3">
					<ul>
                      <li class="dropdown-header"><a href="{% url 'doorlock:greset' %}">Greset Door Lock</a></li>
                      <li><a href="{% url 'doorlock:greset_cylindrical_lock' %}">Cylindrical Lock</a></li>
                      <li><a href="{% url 'doorlock:greset_deadbolt_lock' %}">Deadbolt Lock</a></li>
                      <li><a href="{% url 'doorlock:greset_handle_set' %}">Handle Set</a></li>
                      <li><a href="{% url 'doorlock:greset_tubular_lever' %}">Tubular Lever</a></li>
						<li class="divider"></li>
						<li class="dropdown-header"><a href="{% url 'others:others' %}">Others</a></li>
						<li><a href="{% url 'others:others_staircase' %}">Staircase</a></li>
						<li><a href="{% url 'others:others_wooden_window' %}">Wooden Window</a></li>
						<li><a href="{% url 'others:others_autogate_system' %}">Autogate System</a></li>
						<li><a href="{% url 'others:others_hardware_misc' %}">Hardware Misc</a></li>
					</ul>
				</li>
          </ul>
        </li>
        <li><a href="{% url 'services' %}">Services</a></li>
        <li><a href="{% url 'contact' %}">Contact Us</a></li>
        <li><a href="{% url 'faq' %}">FAQ</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>